# Generated by Django 4.2.1 on 2024-01-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exponant',
            name='img',
        ),
    ]
